#! /bin/sh

# Set up monitors
if [[ $(xrandr -q | grep 'HDMI-2 connected') ]]; then
    xrandr --output HDMI-1 --primary --mode 1920x1080 --rotate normal \
           --output HDMI-2 --mode 1920x1080 --rotate right --right-of HDMI-1
fi

# Workspace monitors
bspc monitor HDMI-1 -d 󰎤 󰎧 󰎪 󰎭 󰎱
bspc monitor HDMI-2 -d 󰎳 󰎶

# Other Stuff
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Autostart
sxhkd &
picom &
xwallpaper --output HDMI-1 --center Pictures/Wallpapers/astral-grave-flowers.png --output HDMI-2 --center Pictures/Wallpapers/ngvJK19.jpeg
$HOME/.config/polybar/launch.sh
